/**
 * Generated by the IBM IDL-to-Java compiler, version 1.0
 * from F:\TestRoot\apps\units\include\PolicyHome.idl
 * Wednesday, June 17, 1998 6:44:40 o'clock AM GMT+00:00
 */
public class Test {
    public static void main(String[] args) {
        //\units
        //无论是代码还是注释中如果出现以\u开头的都会被识别为转移字符，如果这些字符后面未跟4个16进制数字则无法进行编译
        System.out.print("Hell");
        System.out.println("o world");
    }
}
